replicaCount: 2

image:
  repository: rukevweubio/my-nodejsapp
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

env:
  NODE_ENV: production

readinessProbe:
  path: /
  port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10

namespace: my-namespace
