apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-portainer-cluster-admin
subjects:
- kind: ServiceAccount
  name: sa-portainer
  namespace: portainer
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
