apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app
  namespace: dev 
  labels:
    app: my-nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nodejs-app
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      containers:
        - name: my-nodejs-app
          image: rukevweubio/my-nodejsapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /        #
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
