apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-app-service
  namespace: dev 
spec:
  type: NodePort
  selector:
    app: my-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
