name: Node.js CI/CD pipeline with Docker, ECR, SonarCloud, OWASP, and K8s

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: my-nodejs-app
  DOCKER_REGISTRY: docker.io
  ECR_REPOSITORY: my-nodejsapp
  erc_repo: 714748322187.dkr.ecr.us-east-1.amazonaws.com/nodejs-app
  KUBECONFIG_PATH: ${{ secrets.KUBECONFIG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        env: [dev, test, produc]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./nodejs-app
        run: npm install

      - name: Run tests
        working-directory: ./nodejs-app
        run: npm test

      - name: Upload test artifacts
        working-directory: ./nodejs-app
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            test-results/
            coverage/

      - name: OWASP Dependency-Check
        working-directory: ./nodejs-app
        uses: dependency-check/scan-action@v6
        with:
          project: my-nodejs-app
          scan: './'
          format: 'ALL'
          fail-on-vuln: 'true'

      - name: SonarCloud Scan
        working-directory: ./nodejs-app
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=rukevweubio_Gitaction-pipeline-nodejs-ecr-kubernates-deployment \
            -Dsonar.organization=rukevweubio-1 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: ./nodejs-app
        run: docker build -t ${{ env.DOCKER_IMAGE }} .

      - name: Trivy scan Docker image
        working-directory: ./nodejs-app
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_IMAGE }}:latest
          format: 'table'
          exit-code: '1'

      - name: Tag & Push Docker image to Docker Hub
        working-directory: ./nodejs-app
        run: |
          docker tag ${{ env.DOCKER_IMAGE }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-nodejsapp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-nodejsapp:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 714748322187.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag & Push Docker image to ECR
        working-directory: ./nodejs-app
        run: |
          docker tag ${{ env.DOCKER_IMAGE }}:latest ${{ env.erc_repo }}:latest
          docker push ${{ env.erc_repo }}:latest

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $KUBECONFIG_PATH
          export KUBECONFIG=$KUBECONFIG_PATH
          kubectl config view

      - name: Set namespace
        run: |
          if [ "${{ matrix.env }}" == "dev" ]; then
            NAMESPACE="runner-dev"
          elif [ "${{ matrix.env }}" == "test" ]; then
            NAMESPACE="runner-test"
          else
            NAMESPACE="runner-produc"
          fi
          echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV

      - name: Deploy to Kubernetes
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/my-nodejsapp:latest|g" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml -n $NAMESPACE
          kubectl rollout status deployment/myapp -n $NAMESPACE
