name: Node.js CI/CD pipeline with Docker, ECR, SonarCloud, OWASP, and K8s

on:
  push:
    branches: ["main"]

env:
  DOCKER_IMAGE: my-nodejs-app
  DOCKER_REGISTRY: docker.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: nodejs-app/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: ./nodejs-app

      - name: Run tests
        run: npm test
        working-directory: ./nodejs-app

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            nodejs-app/test-results/
            nodejs-app/coverage/

      - name: SonarCloud Scan
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=rukevweubio_Gitaction-pipeline-nodejs-ecr-kubernates-deployment \
            -Dsonar.organization=rukevweubio-1 \
            -Dsonar.sources=./nodejs-app \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE }}:latest ./nodejs-app

      - name: Trivy scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_IMAGE }}:latest
          format: 'table'
          exit-code: '0'

      - name: Tag & Push Docker image to Docker Hub
        run: |
          docker tag ${{ env.DOCKER_IMAGE }}:latest ${{ secrets.DOCKER_USERNAME }}/my-nodejsapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-nodejsapp:latest

      